CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Games" (
    "GameId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Theme" text NOT NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("GameId")
);

CREATE TABLE "Players" (
    "PlayerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Players" PRIMARY KEY ("PlayerId")
);

CREATE TABLE "Questions" (
    "QuestionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionText" text NOT NULL,
    "GameId" integer NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("QuestionId"),
    CONSTRAINT "FK_Questions_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("GameId") ON DELETE CASCADE
);

CREATE TABLE "GamePlayer" (
    "GamesGameId" integer NOT NULL,
    "PlayersPlayerId" integer NOT NULL,
    CONSTRAINT "PK_GamePlayer" PRIMARY KEY ("GamesGameId", "PlayersPlayerId"),
    CONSTRAINT "FK_GamePlayer_Games_GamesGameId" FOREIGN KEY ("GamesGameId") REFERENCES "Games" ("GameId") ON DELETE CASCADE,
    CONSTRAINT "FK_GamePlayer_Players_PlayersPlayerId" FOREIGN KEY ("PlayersPlayerId") REFERENCES "Players" ("PlayerId") ON DELETE CASCADE
);

CREATE TABLE "Options" (
    "OptionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "QuestionId" integer NOT NULL,
    "Description" text NOT NULL,
    "IsCorrect" boolean NOT NULL,
    CONSTRAINT "PK_Options" PRIMARY KEY ("OptionId"),
    CONSTRAINT "FK_Options_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("QuestionId") ON DELETE CASCADE
);

CREATE TABLE "PlayerAnswers" (
    "PlayerAnswerId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlayerId" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "OptionId" integer NOT NULL,
    "Pontos" integer NOT NULL,
    "GameId" integer,
    CONSTRAINT "PK_PlayerAnswers" PRIMARY KEY ("PlayerAnswerId"),
    CONSTRAINT "FK_PlayerAnswers_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("GameId"),
    CONSTRAINT "FK_PlayerAnswers_Options_OptionId" FOREIGN KEY ("OptionId") REFERENCES "Options" ("OptionId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerAnswers_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("PlayerId") ON DELETE CASCADE,
    CONSTRAINT "FK_PlayerAnswers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("QuestionId") ON DELETE CASCADE
);

CREATE INDEX "IX_GamePlayer_PlayersPlayerId" ON "GamePlayer" ("PlayersPlayerId");

CREATE INDEX "IX_Options_QuestionId" ON "Options" ("QuestionId");

CREATE INDEX "IX_PlayerAnswers_GameId" ON "PlayerAnswers" ("GameId");

CREATE INDEX "IX_PlayerAnswers_OptionId" ON "PlayerAnswers" ("OptionId");

CREATE INDEX "IX_PlayerAnswers_PlayerId" ON "PlayerAnswers" ("PlayerId");

CREATE INDEX "IX_PlayerAnswers_QuestionId" ON "PlayerAnswers" ("QuestionId");

CREATE INDEX "IX_Questions_GameId" ON "Questions" ("GameId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240703201209_CriacaoTabelas', '8.0.6');

COMMIT;

